# Generated by Django 4.1.4 on 2022-12-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=30)),
                ('Mobile', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
            ],
        ),
    ]
